const languages = {
  ru: {
    header: {
      search: "Поиск",
      products: "Продукты",
    },
    sitebar: {
      productList: "Список продуктов",
      category: "Категории",
      atribut: "Атрибуты",
      order: "Заказы",
      recall: "Обратный связ",
      settings: "Настройки сайта",
      exit: "Выйти",
    },
    main: {
      filter: "Фильтр",
      searchProduct: "Поиск товара ",
      sort: "Сортировка",
      as: "По А-Я",
      add: "Добавить",
      select: "Выбрано",
      productName: "Название товара",
      price: "Цена",
      salePrice: "Цена со скидкой",
      quantity: "Кол-во",
      size: "Размер",
      volume: "Объем",
      status: "Статус",
      elementsPage: "Элементы на каждой странице",
      itemsNumb: " из  предметов",
      pages: "из  страниц",
      sum: "сум",
      delete: "Удалить",
      addProduct: "Добавить продукт",
      information: "Информация",
      picture: "Изображение",
      colvo: "Кол-во под категория",
      subCat: "Под категории",
    },
  },
  en: {
    header: {
      search: "Search",
      products: "Products",
    },
    sitebar: {
      productList: "Products Lists",
      category: "Category",
      atribut: "Attribute",
      order: "Order",
      recall: "Feedback",
      settings: "Site settings",
      exit: "Exit",
    },

    main: {
      filter: "Filter",
      searchProduct: "Search products ",
      sort: "Sort",
      as: "By A-Z",
      add: "Add",
      select: "Selected",
      productName: "Product Name",
      price: "Price",
      salePrice: "Sale Price",
      quantity: "Q-ty",
      size: "Size",
      volume: "Volume",
      status: "Status",
      elementsPage: "Elements on each page",
      itemsNumb: " out of  items",
      pages: "of  pages",
      sum: "sum",
      delete: "Delete",
      addProduct: "Add Products",
      information: "Information",
      picture: "Picture",
      colvo: "Q-ty sub category",
      subCat: "Sub categories",
    },
  },
  uz: {
    header: {
      search: "Qidiruv",
      products: "Mahsulotlar",
    },
    sitebar: {
      productList: "Mahsulotlar ro'yxati",
      category: "Kategoriyalar",
      atribut: "Attributlar",
      order: "Buyurtma",
      recall: "Fikr-mulohaza",
      settings: "Sayt sozlamalari",
      exit: "Chiqish",
    },

    main: {
      filter: "Filter",
      searchProduct: "Mahsulot qidirish",
      sort: "Saralash",
      as: "A-Z tomonidan",
      add: "Qo'shish",
      select: "Tanlangan",
      productName: "Mahsulot nomi",
      price: "Narx",
      salePrice: "Chegirma narx",
      quantity: "Soni",
      size: "O'lcham",
      volume: "Hajm",
      status: "Status",
      elementsPage: "Har bir sahifadagi elementlar",
      itemsNumb: " elementdan  tasi",
      pages: " sahifadan iborat",
      sum: "so'm",
      delete: "O'chirish",
      addProduct: "Mahsulot qo'shish",
      information: "Ma'lumot",
      picture: "Rasm",
      colvo: "Kategoriya bo'yicha soni",
      subCat: "Sub kategoriyalar",
    },
  },
};

export default languages;
